### ISSUE TITLE
As a user I want to keep a list of my favorite restaurants

### ISSUE THREAD

**Issue by anna-averianova** [SEP007/lmvc-patat#56]
# Tasks
- [x] Add new table for favorite locations
- [x] Add a model for new tables
- [x] Add methods to Locations model to get a list of favorites
- [x] Change Restaurant view to integrate stars for favoriting
- [x] Make clicking stars do work for locations
- [x] Add a view for listing favorite locations
- [x] Hide favoriting from not logged in stalkers
- [x] Prettify favorite views (locations)
- [x] Add a border around tabs available in My Favorites
## Additions

Distance & address & telephone num
### Acceptance test
- Unfavorite and favorite
- Redirection to the restaurants home
