### ISSUE TITLE
As a user, I want a pretty view for favorite dishes

### ISSUE THREAD

**Issue by anna-averianova** [SEP007/lmvc-patat#57]
# Tasks
- [x] Prettify favorite views (dishes)
- [x] Add an icon "currently on offer" to favorite dish view
- [x] Add a function to calculate the distance between a user and a dish
- [x] Add a border around tabs available in My Favorites
### Acceptance test
- On offer is updated when the dish is updated
- Distance is the same as the dish view
