### ISSUE TITLE
As a user I want to keep a list of my favorite dishes

### ISSUE THREAD

**Issue by tdeekens** [SEP007/lmvc-patat#8]
At this point in time the user will always be presented with a the dishes without any options to narrow them down.
# Tasks
- [x] Add a new table for favorite dishes
- [x] Add a model for new table
- [x] Add methods to Dishes model to get a list of favorites
- [x] Add a new controller for Favorites
- [x] Change Dishes view to integrate stars for favoriting
- [x] Make clicking stars do work for dishes
- [x] Add a view for listing favorite dishes
- [x] Hide favoriting from not logged in stalkers
